platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine/git
    tag: latest

outputs:
- name: artifacts
inputs:
- name: postgres-repo
- name: patches
- name: postgres-patch-ci

run:
  path: postgres-patch-ci/tasks/apply-patch/run.sh
