platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: latest

inputs:
- name: postgres-repo-tarball
- name: postgres-patch-ci

run:
  path: postgres-patch-ci/tasks/run-tests/run.sh
