platform: linux

image_resource:
  type: docker-image
  source:
    repository: appropriate/curl

inputs:
- name: patches
- name: postgres-patch-ci

run:
  path: postgres-patch-ci/tasks/alert-slack-for-patch/run.sh
