platform: linux

image_resource:
  type: docker-image
  source:
    repository: appropriate/curl

inputs:
- name: postgres-repo-tarball
- name: postgres-patch-ci
- name: build-metadata

run:
  path: postgres-patch-ci/tasks/alert-slack/run.sh
